
import django
django.setup()
from table.models import *

def make_resource(**kwargs):
    tmp = Resource(**kwargs)
    tmp.save()
    return tmp

def make_country(**kwargs):
    tmp = Country(**kwargs)
    tmp.save()
    return tmp

def make_card(**kwargs):
    tmp = Card(**kwargs)
    tmp.save()
    return tmp

Resource.objects.all().delete()
Card.objects.all().delete()
Country.objects.all().delete()
VirtualContest.objects.all().delete()
NeedsCardResource.objects.all().delete()
NeedsCardResource.objects.all().delete()
c_junior_test = VirtualContest(id=3, name="Младшая зимняя олимпиада (ТЕСТ)", login_prefix="sis-2023-0junior")
c_junior_test.save()
c_adult_test = VirtualContest(id=4, name="Старшая зимняя олимпиада (ТЕСТ)", login_prefix="sis-2023-0adult")
c_adult_test.save()
c_junior = VirtualContest(id=1, name="Младшая зимняя олимпиада", login_prefix="sis-2023-w-jun")
c_junior.save()
c_adult = VirtualContest(id=2, name="Старшая зимняя олимпиада", login_prefix="sis-2023-w-sen")
c_adult.save()
r0 = make_resource(id=1,name='поток',name_acc_one='поток',name_acc_two='потока',name_acc_five='потоков', color='green', gender=Gender.MALE.value)
r1 = make_resource(id=2,name='ссылка',name_acc_one='ссылку',name_acc_two='ссылки',name_acc_five='ссылок', color='yellow', gender=Gender.FEMALE.value)
r2 = make_resource(id=3,name='указатель',name_acc_one='указатель',name_acc_two='указателя',name_acc_five='указателей', color='blue', gender=Gender.MALE.value)
r3 = make_resource(id=4,name='вода',name_acc_one='воду',name_acc_two='воды',name_acc_five='воды', color='red', gender=Gender.FEMALE.value)

no = make_country(id=1, name='Русь', name_gen='Руси', bonus=5)
# Челябинская операция
# Битва за Каменск-Уральский
# Холмистая засада
# Долина Демидовская
# Судьбоносный поход в Нижний Тагил
# Пермский рубеж
zb = make_country(id=2, name='Забайкалье', name_gen='Забайкалья', bonus=5)
# Битва за Забайкальск
# Хилокский перевал
# Борьба за Улан-Удэ
# Тункинская долина
# Байкальский фронт
pb = make_country(id=3, name='Прибайкалье', name_gen='Прибайкалья', bonus=5)
# Битва на мысе Лисий
# Схватка у подножия хребта Каменск
# Борьба за поселок Хужир
# Решающее столкновение в Северобайкальске
# Прибайкальский фронт
kk = make_country(id=4, name='Кавказ', name_gen='Кавказа', bonus=5)
# Хребет Бештау
# Битва за Эльбрус
# Долина реки Терек
# Страстная Долина
# Крепость Хашури
pm = make_country(id=5, name='Примосковье', name_gen='Примосковья', bonus=5)
# Битва у подножия горы Лисья
# Тверская стенка
# Борьба за Чёрное озеро
# Коломенская крепость
# Подмосковный фронт
bl = make_country(id=6, name='Прибалтика', name_gen='Прибалтики', bonus=5)
# Сражение у побережья Лиепаи
# Захват Яунгшилы
# Битва за Куршскую косу
# Нацеленность на Нарву
# Балтийский фронт
mo = make_country(id=7, name='Луна', name_gen='Луны', bonus=5)
# Море Тишини
# Кратер Хармонии
# Долина Рассвета
# Гора Аристарх
# Лунное ущелье

card = make_card(ejudge_short_name="13", name="Битва на ферме", score=3, level=1, country=no, photo=1, polygon_short_name="replace-digits-eleven")
c_junior.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=1).save()

card = make_card(ejudge_short_name="13", name="Битва на ферме", score=3, level=1, country=no, photo=1, polygon_short_name="replace-digits-eleven")
c_junior_test.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=1).save()

card = make_card(ejudge_short_name="13", name="Битва на ферме", score=1, level=0, country=no, photo=1, polygon_short_name="replace-digits-eleven")
c_adult.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="13", name="Битва на ферме", score=1, level=0, country=no, photo=1, polygon_short_name="replace-digits-eleven")
c_adult_test.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="21", name="Ящер на холме", score=1, level=1, country=no, photo=2, polygon_short_name="canaries")
c_junior.cards.add(card)
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="21", name="Ящер на холме", score=1, level=1, country=no, photo=2, polygon_short_name="canaries")
c_junior_test.cards.add(card)
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="22", name="Прогулка по лесу", score=2, level=1, country=no, photo=3, polygon_short_name="beautiful-strings")
c_junior.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="22", name="Прогулка по лесу", score=2, level=1, country=no, photo=3, polygon_short_name="beautiful-strings")
c_junior_test.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="28", name="Сбор припасов", score=2, level=0, country=no, photo=4, polygon_short_name="gt-lt")
c_adult.cards.add(card)
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="28", name="Сбор припасов", score=2, level=0, country=no, photo=4, polygon_short_name="gt-lt")
c_adult_test.cards.add(card)
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="5", name="Военная хитрость древних русов (валун)", score=2, level=0, country=no, photo=5, polygon_short_name="shift-and-reverse")
c_adult.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="5", name="Военная хитрость древних русов (валун)", score=2, level=0, country=no, photo=5, polygon_short_name="shift-and-reverse")
c_adult_test.cards.add(card)
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="9", name="Помощь Перуна", score=2, level=2, country=no, photo=6, polygon_short_name="pairs-of-perpendicular-vectors")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="9", name="Помощь Перуна", score=2, level=2, country=no, photo=6, polygon_short_name="pairs-of-perpendicular-vectors")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="9", name="Помощь Перуна", score=2, level=1, country=no, photo=6, polygon_short_name="pairs-of-perpendicular-vectors")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="9", name="Помощь Перуна", score=2, level=1, country=no, photo=6, polygon_short_name="pairs-of-perpendicular-vectors")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="15", name="Дуэль", score=3, level=2, country=no, photo=7, polygon_short_name="beresta")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="15", name="Дуэль", score=3, level=2, country=no, photo=7, polygon_short_name="beresta")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="15", name="Дуэль", score=5, level=1, country=no, photo=7, polygon_short_name="beresta")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="15", name="Дуэль", score=5, level=1, country=no, photo=7, polygon_short_name="beresta")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="8", name="Неожиданная помощь", score=2, level=2, country=no, photo=8, polygon_short_name="newyear-tree")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="8", name="Неожиданная помощь", score=2, level=2, country=no, photo=8, polygon_short_name="newyear-tree")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="8", name="Неожиданная помощь", score=2, level=1, country=no, photo=8, polygon_short_name="newyear-tree")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="8", name="Неожиданная помощь", score=2, level=1, country=no, photo=8, polygon_short_name="newyear-tree")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="7", name="Заморская подмога", score=6, level=2, country=no, photo=9, polygon_short_name="uwuanime")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="7", name="Заморская подмога", score=6, level=2, country=no, photo=9, polygon_short_name="uwuanime")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="7", name="Заморская подмога", score=7, level=1, country=no, photo=9, polygon_short_name="uwuanime")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="7", name="Заморская подмога", score=7, level=1, country=no, photo=9, polygon_short_name="uwuanime")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="20", name="Гонка на птеродимирах", score=3, level=2, country=no, photo=10, polygon_short_name="navigator")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()

card = make_card(ejudge_short_name="20", name="Гонка на птеродимирах", score=3, level=2, country=no, photo=10, polygon_short_name="navigator")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()

card = make_card(ejudge_short_name="16", name="Черное озеро", score=3, level=2, country=no, photo=11, polygon_short_name="frog")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=2).save()
NeedsCardResource(card=card, resource=r2, count=2).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="16", name="Черное озеро", score=3, level=2, country=no, photo=11, polygon_short_name="frog")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=2).save()
NeedsCardResource(card=card, resource=r2, count=2).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="19", name="Подводная стычка", score=4, level=2, country=no, photo=12, polygon_short_name="cave")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="19", name="Подводная стычка", score=4, level=2, country=no, photo=12, polygon_short_name="cave")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="19", name="Подводная стычка", score=3, level=1, country=no, photo=12, polygon_short_name="cave")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="19", name="Подводная стычка", score=3, level=1, country=no, photo=12, polygon_short_name="cave")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="27", name="Битва на мосту", score=4, level=1, country=no, photo=13, polygon_short_name="neural-xor")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()

card = make_card(ejudge_short_name="27", name="Битва на мосту", score=4, level=1, country=no, photo=13, polygon_short_name="neural-xor")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=2).save()
NeedsCardResource(card=card, resource=r2, count=1).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()

card = make_card(ejudge_short_name="29", name="Стратегическое совещание", score=4, level=1, country=no, photo=14, polygon_short_name="dividing-a-string")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=2).save()
NeedsCardResource(card=card, resource=r2, count=2).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="29", name="Стратегическое совещание", score=4, level=1, country=no, photo=14, polygon_short_name="dividing-a-string")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=2).save()
NeedsCardResource(card=card, resource=r2, count=2).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="10", name="Контратака под Тывой", score=5, level=3, country=no, photo=15, polygon_short_name="white-word")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=3).save()
NeedsCardResource(card=card, resource=r2, count=3).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="10", name="Контратака под Тывой", score=5, level=3, country=no, photo=15, polygon_short_name="white-word")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=3).save()
NeedsCardResource(card=card, resource=r2, count=3).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="10", name="Контратака под Тывой", score=8, level=2, country=no, photo=15, polygon_short_name="white-word")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=3).save()
NeedsCardResource(card=card, resource=r2, count=3).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="10", name="Контратака под Тывой", score=8, level=2, country=no, photo=15, polygon_short_name="white-word")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=3).save()
NeedsCardResource(card=card, resource=r2, count=3).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="14", name="Судьбоносный поход в Нижний Тагил", score=4, level=3, country=no, photo=16, polygon_short_name="strange-probability")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=7).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="14", name="Судьбоносный поход в Нижний Тагил", score=4, level=3, country=no, photo=16, polygon_short_name="strange-probability")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=7).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="14", name="Судьбоносный поход в Нижний Тагил", score=3, level=2, country=no, photo=16, polygon_short_name="strange-probability")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=7).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="14", name="Судьбоносный поход в Нижний Тагил", score=3, level=2, country=no, photo=16, polygon_short_name="strange-probability")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r1, count=7).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="11", name="Помощь Сварога", score=5, level=3, country=no, photo=17, polygon_short_name="winter-olymp-wikipedia-quiz-2023-part-one")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="11", name="Помощь Сварога", score=5, level=3, country=no, photo=17, polygon_short_name="winter-olymp-wikipedia-quiz-2023-part-one")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="11", name="Помощь Сварога", score=4, level=2, country=no, photo=17, polygon_short_name="winter-olymp-wikipedia-quiz-2023-part-one")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="11", name="Помощь Сварога", score=4, level=2, country=no, photo=17, polygon_short_name="winter-olymp-wikipedia-quiz-2023-part-one")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="6", name="Династический брак", score=5, level=3, country=no, photo=18, polygon_short_name="wayback-machine")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=3).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="6", name="Династический брак", score=5, level=3, country=no, photo=18, polygon_short_name="wayback-machine")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=3).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="6", name="Династический брак", score=4, level=2, country=no, photo=18, polygon_short_name="wayback-machine")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=3).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="6", name="Династический брак", score=4, level=2, country=no, photo=18, polygon_short_name="wayback-machine")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=3).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="23", name="Битва за Улан-Уде", score=6, level=3, country=no, photo=19, polygon_short_name="tree")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="23", name="Битва за Улан-Уде", score=6, level=3, country=no, photo=19, polygon_short_name="tree")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="25", name="Спасение Олега и Михайло из плена Ящеров", score=5, level=3, country=no, photo=20, polygon_short_name="messages")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=5).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="25", name="Спасение Олега и Михайло из плена Ящеров", score=5, level=3, country=no, photo=20, polygon_short_name="messages")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=5).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="26", name="Осада Эльбруса", score=4, level=3, country=no, photo=21, polygon_short_name="ascii-sides")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="26", name="Осада Эльбруса", score=4, level=3, country=no, photo=21, polygon_short_name="ascii-sides")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="24", name="Русы и ящеры встречают Новый Год", score=5, level=3, country=no, photo=22, polygon_short_name="bit-div-mul-parity")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="24", name="Русы и ящеры встречают Новый Год", score=5, level=3, country=no, photo=22, polygon_short_name="bit-div-mul-parity")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="30", name="Подлая засада", score=7, level=2, country=no, photo=23, polygon_short_name="folia")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="30", name="Подлая засада", score=7, level=2, country=no, photo=23, polygon_short_name="folia")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=1).save()
NeedsCardResource(card=card, resource=r1, count=1).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="3", name="Пир древних русов", score=6, level=2, country=no, photo=24, polygon_short_name="greedy-division")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=5).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="3", name="Пир древних русов", score=6, level=2, country=no, photo=24, polygon_short_name="greedy-division")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=5).save()
GivesCardResource(card=card, resource=r0, count=2).save()
GivesCardResource(card=card, resource=r1, count=3).save()
GivesCardResource(card=card, resource=r2, count=2).save()

card = make_card(ejudge_short_name="31", name="Взятие высоты", score=5, level=2, country=no, photo=25, polygon_short_name="shortest-path-on-line")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="31", name="Взятие высоты", score=5, level=2, country=no, photo=25, polygon_short_name="shortest-path-on-line")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=4).save()
NeedsCardResource(card=card, resource=r1, count=5).save()
NeedsCardResource(card=card, resource=r2, count=4).save()
GivesCardResource(card=card, resource=r0, count=1).save()
GivesCardResource(card=card, resource=r1, count=2).save()
GivesCardResource(card=card, resource=r2, count=1).save()

card = make_card(ejudge_short_name="1", name="Танцевальный баттл", score=6, level=2, country=no, photo=26, polygon_short_name="distinct-numbers")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="1", name="Танцевальный баттл", score=6, level=2, country=no, photo=26, polygon_short_name="distinct-numbers")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=6).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r0, count=3).save()
GivesCardResource(card=card, resource=r1, count=1).save()
GivesCardResource(card=card, resource=r2, count=3).save()

card = make_card(ejudge_short_name="12", name="Путешествие на Луну", score=7, level=4, country=no, photo=27, polygon_short_name="antti-laaksonen-binary-guess")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=9).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="12", name="Путешествие на Луну", score=7, level=4, country=no, photo=27, polygon_short_name="antti-laaksonen-binary-guess")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=9).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="12", name="Путешествие на Луну", score=9, level=3, country=no, photo=27, polygon_short_name="antti-laaksonen-binary-guess")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=9).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="12", name="Путешествие на Луну", score=9, level=3, country=no, photo=27, polygon_short_name="antti-laaksonen-binary-guess")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=9).save()
NeedsCardResource(card=card, resource=r1, count=6).save()
NeedsCardResource(card=card, resource=r2, count=6).save()
GivesCardResource(card=card, resource=r3, count=1).save()

card = make_card(ejudge_short_name="17", name="Битва за Москву", score=9, level=4, country=no, photo=28, polygon_short_name="parking")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=9).save()

card = make_card(ejudge_short_name="17", name="Битва за Москву", score=9, level=4, country=no, photo=28, polygon_short_name="parking")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=9).save()

card = make_card(ejudge_short_name="18", name="Высадка в подмосковье", score=9, level=4, country=no, photo=29, polygon_short_name="milk-scheduling")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=9).save()
NeedsCardResource(card=card, resource=r2, count=6).save()

card = make_card(ejudge_short_name="18", name="Высадка в подмосковье", score=9, level=4, country=no, photo=29, polygon_short_name="milk-scheduling")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=9).save()
NeedsCardResource(card=card, resource=r2, count=6).save()

card = make_card(ejudge_short_name="2", name="Защита Гипербореи", score=9, level=4, country=no, photo=30, polygon_short_name="three")
c_junior.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=7).save()
NeedsCardResource(card=card, resource=r2, count=7).save()

card = make_card(ejudge_short_name="2", name="Защита Гипербореи", score=9, level=4, country=no, photo=30, polygon_short_name="three")
c_junior_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=7).save()
NeedsCardResource(card=card, resource=r2, count=7).save()

card = make_card(ejudge_short_name="2", name="Защита Гипербореи", score=8, level=3, country=no, photo=30, polygon_short_name="three")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=7).save()
NeedsCardResource(card=card, resource=r2, count=7).save()

card = make_card(ejudge_short_name="2", name="Защита Гипербореи", score=8, level=3, country=no, photo=30, polygon_short_name="three")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=7).save()
NeedsCardResource(card=card, resource=r2, count=7).save()

card = make_card(ejudge_short_name="4", name="Тверская Стенка", score=10, level=3, country=no, photo=31, polygon_short_name="nand-tree")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=9).save()

card = make_card(ejudge_short_name="4", name="Тверская Стенка", score=10, level=3, country=no, photo=31, polygon_short_name="nand-tree")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=5).save()
NeedsCardResource(card=card, resource=r1, count=4).save()
NeedsCardResource(card=card, resource=r2, count=9).save()

card = make_card(ejudge_short_name="32", name="Абордаж", score=10, level=3, country=no, photo=32, polygon_short_name="one-or-two")
c_adult.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=9).save()
NeedsCardResource(card=card, resource=r2, count=6).save()

card = make_card(ejudge_short_name="32", name="Абордаж", score=10, level=3, country=no, photo=32, polygon_short_name="one-or-two")
c_adult_test.cards.add(card)
NeedsCardResource(card=card, resource=r0, count=7).save()
NeedsCardResource(card=card, resource=r1, count=9).save()
NeedsCardResource(card=card, resource=r2, count=6).save()

c_junior.save()
c_junior_test.save()
c_adult.save()
c_adult_test.save()
