# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-24 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Closed'), (1, 'Opened'), (2, 'Read'), (3, 'Tried'), (4, 'Solved')], db_index=True, validators=[djchoices.choices.ChoicesValidator({0: 'Closed', 1: 'Opened', 2: 'Read', 3: 'Tried', 4: 'Solved'})])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='table.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
