# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-24 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20171224_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivesCardResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NeedsCardResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='gives',
        ),
        migrations.RemoveField(
            model_name='card',
            name='needs',
        ),
        migrations.AddField(
            model_name='needscardresource',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Card'),
        ),
        migrations.AddField(
            model_name='needscardresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Resource'),
        ),
        migrations.AddField(
            model_name='givescardresource',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Card'),
        ),
        migrations.AddField(
            model_name='givescardresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Resource'),
        ),
        migrations.AddField(
            model_name='card',
            name='gives',
            field=models.ManyToManyField(related_name='_card_gives_+', through='table.GivesCardResource', to='table.Resource'),
        ),
        migrations.AddField(
            model_name='card',
            name='needs',
            field=models.ManyToManyField(related_name='_card_needs_+', through='table.NeedsCardResource', to='table.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='needscardresource',
            unique_together=set([('card', 'resource')]),
        ),
        migrations.AlterUniqueTogether(
            name='givescardresource',
            unique_together=set([('card', 'resource')]),
        ),
    ]
