# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20171224_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='level',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
