# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_auto_20171230_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_regex', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('cards', models.ManyToManyField(related_name='contest', to='table.Card')),
            ],
        ),
        migrations.RemoveField(
            model_name='contest',
            name='cards',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
