# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-30 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_country_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualcontest',
            old_name='login_regex',
            new_name='login_prefix',
        ),
    ]
