# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_auto_20171230_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_gen',
            field=models.CharField(default='', help_text='Например, Германии', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='color',
            field=models.CharField(default='', help_text='blue, color, red или green', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='name_acc_five',
            field=models.CharField(default='', help_text='Например, (пять) пушек', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='name_acc_one',
            field=models.CharField(default='', help_text='Например, (одну) пушку', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='name_acc_two',
            field=models.CharField(default='', help_text='Например, (две) пушки', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='Имя карты/замка', max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Например, Германия', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(help_text='Например, пушка', max_length=255),
        ),
    ]
