# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-30 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('table', '0012_card_photo_id'), ('table', '0013_auto_20171230_2349'), ('table', '0014_remove_card_photo'), ('table', '0015_card_photo')]

    dependencies = [
        ('table', '0011_auto_20171231_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='photo',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
