# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-30 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_card_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='photo_id',
            new_name='photo',
        ),
    ]
