# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-31 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0013_auto_20171231_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Neuter')]),
        ),
    ]
