# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-30 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0013_auto_20171230_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='photo',
        ),
    ]
