# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0014_auto_20171231_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='polygon_short_name',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
